-- Creation of customer table
CREATE TABLE IF NOT EXISTS customer (
    id             serial           NOT NULL PRIMARY KEY,
    first_name      varchar(250)    NOT NULL,
    last_name       varchar(250)    NOT NULL,
    company_name    varchar(250)    NOT NULL
);


INSERT INTO customer(first_name,last_name,company_name) VALUES ('Abigail', 'Allen', 'New Relic');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Abigail','Ferguson','New Relic');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Abraham','Johnston','New Relic');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Ada','Anderson','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Adelaide','Robinson','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Adele','Craig','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Adison','Mitchell','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Adison','Johnson','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Adrianna','Myers','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Aiden','Henderson','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Albert','Turner','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Alberta','Morrison','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Alberta','Parker','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Alberta','Montgomery','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Aldus','Holmes','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Alen','Morris','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Alen','Kelly','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Alexander','Carter','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Alexander','Payne','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Alexander','Ryan','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Alexander','Bennett','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Alfred','Clark','Google');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Alisa','Warren','Google');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Alissa','Ferguson','Google');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Amber','Russell','Google');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Andrew','Richardson','Google');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Andrew','Murray','Google');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Annabella','Thomas','Google');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Annabella','Hamilton','Google');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Antony','Miller','Google');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Antony','Davis','Google');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Antony','Hawkins','Google');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Ashton','Parker','Google');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Ashton','Andrews','Google');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Belinda','Stevens','Google');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Belinda','Kelly','Google');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Belinda','Adams','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Belinda','Elliott','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Brad','Reed','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Brianna','Crawford','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Briony','Ferguson','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Briony','Nelson','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Byron','Stewart','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Cadie','Andrews','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Camila','Johnston','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Carina','Alexander','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Carlos','Thompson','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Carlos','Edwards','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Catherine','Howard','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Charlotte','Stevens','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Chelsea','Grant','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Cherry','Richards','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Cherry','Kelley','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Chloe','Richards','Bluth Company');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Connie','Cunningham','New Relic');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Dainton','Holmes','New Relic');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Dale','Holmes','New Relic');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Dale','Hunt','New Relic');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Daniel','Brown','New Relic');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Daniel','Rogers','New Relic');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Darcy','Wells','New Relic');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Daryl','Wilson','Capital One');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Daryl','Warren','Capital One');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Daryl','Williams','Capital One');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('David','Fowler','Capital One');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('David','Bailey','Capital One');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('David','Taylor','Capital One');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Deanna','Spencer','Capital One');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Dexter','Brown','Capital One');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Dexter','Carroll','Capital One');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Dexter','Higgins','Capital One');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Dominik','Murray','Capital One');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Dominik','Allen','Capital One');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Eddy','Brooks','Capital One');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Eddy','Kelly','Pokemon');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Edgar','Thompson','Pokemon');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Edwin','Carter','Pokemon');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Elian','Parker','Pokemon');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Elise','Morrison','Pokemon');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Ellia','Johnson','Pokemon');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Ellia','Cameron','Pokemon');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Emma','Craig','Pokemon');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Eric','Smith','Pokemon');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Evelyn','Ross','Pokemon');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Evelyn','Murray','Pokemon');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Florrie','Evans','Pokemon');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Frederick','Edwards','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Garry','Campbell','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Gianna','Hall','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Gianna','Robinson','Nintendo');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Gianna','Brown','Nintendo');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Gianna','Spencer','Nintendo');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Gianna','Richards','Nintendo');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Hailey','Edwards','Nintendo');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Haris','Richardson','Nintendo');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Harold','Allen','Nintendo');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Henry','Hunt','Nintendo');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Isabella','Mason','Nintendo');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Jack','Williams','Splunk');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Jacob','Harrison','Splunk');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('James','Parker','Splunk');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Jared','Stevens','Splunk');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Jared','Hawkins','Splunk');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Jasmine','Farrell','Splunk');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Jenna','Taylor','Splunk');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Jessica','Casey','Business');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Jessica','Grant','Business');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Jessica','Hall','Business');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Jessica','Hamilton','Business');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('John','Craig','Business');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Jordan','Harrison','Business');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Joyce','Cameron','Nintendo');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Joyce','Stevens','Nintendo');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Julia','Hill','Nintendo');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Justin','Lloyd','Nintendo');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Kellan','Hunt','Nintendo');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Kevin','Johnston','Nintendo');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Kirsten','Stevens','Nintendo');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Kristian','Reed','Nintendo');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Lana','Craig','Nintendo');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Lana','Ross','Nintendo');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Lenny','Stewart','Nintendo');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Lilianna','Lloyd','Nintendo');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Lilianna','Craig','Nintendo');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Lucia','Hall','Nintendo');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Lucy','Moore','Nintendo');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Lucy','Wilson','Business');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Luke','Brooks','Business');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Lyndon','Fowler','Business');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Marcus','Barnes','Business');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Maria','Owens','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Max','Andrews','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Maximilian','Myers','Github');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Maximilian','Thompson','Github');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Maya','Warren','Github');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Maya','Hill','Github');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Melanie','Campbell','Github');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Melanie','Parker','Github');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Michael','Chapman','Github');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Michael','Bennett','Github');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Miller','Carroll','Github');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Miller','Elliott','Github');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Naomi','Edwards','Github');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Natalie','Watson','Github');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Ned','Alexander','Github');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Ned','Smith','Github');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Nicholas','Mason','Github');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Olivia','Wright','Gobias');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Owen','Mason','Gobias');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Owen','Bennett','Gobias');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Paige','Morgan','Gobias');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Paige','Murphy','Gobias');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Paul','Lloyd','Gobias');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Penelope','Chapman','Gobias');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Penelope','Gibson','Gobias');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Penelope','Grant','Gobias');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Penelope','Morrison','Gobias');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Rafael','Tucker','Gobias');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Rafael','Cunningham','Sportify');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Rafael','Morgan','Sportify');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Rebecca','Kelly','Sportify');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Reid','Mitchell','Sportify');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Robert','Turner','Sportify');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Roland','Ellis','Sportify');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Roland','Adams','Sportify');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Roland','Myers','Sportify');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Roland','Dixon','Sportify');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Roman','Higgins','Sportify');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Roman','Stewart','Sportify');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Rosie','Payne','Sportify');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Ryan','Edwards','TestData');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Sabrina','Ferguson','TestData');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Samantha','Barnes','Gitlab');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Samantha','Johnston','Gitlab');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Sarah','Anderson','Gitlab');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Sarah','Bailey','Gitlab');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Savana','Wright','Gitlab');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Sawyer','Murphy','Gitlab');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Sienna','Armstrong','Gitlab');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Sienna','Jones','Gitlab');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Sophia','Perry','Gitlab');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Sophia','Fowler','Gitlab');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Steven','Baker','Gitlab');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Stuart','Andrews','Gitlab');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Stuart','Carroll','Gitlab');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Sydney','Stevens','Gitlab');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Tara','Kelly','Gitlab');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Tess','Higgins','Gitlab');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Thomas','Clark','TestData');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Thomas','Thompson','TestData');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Tiana','West','TestData');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Tony','Brooks','TestData');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Valeria','Murphy','TestData');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Vanessa','Smith','TestData');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Victor','Ross','TestData');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Victoria','Crawford','TestData');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Vincent','Scott','TestData');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Vivian','Crawford','TestData');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Vivian','Martin','TestData');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('William','Spencer','Gobias');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Abigail','Myers','Climate LLC');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Adelaide','Carter','Climate LLC');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Adelaide','Mitchell','Climate LLC');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Agata','Jones','Climate LLC');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Alan','Harrison','Climate LLC');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Alan','Evans','Climate LLC');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Alan','Hall','Climate LLC');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Alberta','Mitchell','Climate LLC');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Alberta','Richards','Climate LLC');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Alberta','Stewart','Climate LLC');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Aldus','Higgins','Climate LLC');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Alexia','Armstrong','Climate LLC');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Alfred','Thomas','Climate LLC');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Alina','Kelly','Climate LLC');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Alisa','Brooks','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Alissa','Foster','Facebook');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Alissa','Owens','Facebook');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Amanda','Barnes','Facebook');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Amy','Walker','Facebook');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Amy','Hamilton','Facebook');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Anna','Gibson','Facebook');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Antony','Davis','Facebook');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('April','Stewart','Facebook');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Arnold','Roberts','Facebook');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Arthur','Perkins','Facebook');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Ashton','Hunt','Facebook');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Ashton','Elliott','Facebook');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Audrey','Russell','Facebook');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Audrey','Nelson','Facebook');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Belinda','Cunningham','Facebook');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Belinda','Murphy','Facebook');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Blake','Armstrong','Facebook');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Blake','Johnston','The Government');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Blake','Cooper','The Government');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Brianna','Bennett','The Government');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Briony','Johnston','The Government');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Briony','Cooper','The Government');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Brooke','Murphy','Dun & Bradstreet Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Byron','Edwards','Dun & Bradstreet Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Cadie','Edwards','Dun & Bradstreet Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Cadie','Cameron','Dun & Bradstreet Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Cadie','Carter','Dun & Bradstreet Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Carl','Edwards','Dun & Bradstreet Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Carl','Cameron','Dun & Bradstreet Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Carlos','Richards','Dun & Bradstreet Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Carlos','Gibson','Dun & Bradstreet Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Catherine','Hall','Dun & Bradstreet Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Charlie','Stewart','Dun & Bradstreet Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Charlotte','Clark','The Government');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Chelsea','Murphy','The Government');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Chelsea','Roberts','The Government');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Chester','Russell','	Airborne, Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Chester','Mitchell','	Airborne, Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Chloe','Perkins','	Airborne, Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Chloe','Murphy','	Airborne, Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Chloe','Smith','	Airborne, Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Clark','Thomas','	Airborne, Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Connie','Perkins','	Airborne, Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Connie','Ferguson','	Airborne, Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Dainton','Martin','	Airborne, Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Daisy','Barnes','	Airborne, Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Dale','Parker','	Airborne, Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Daniel','Russell','	Airborne, Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Daniel','Armstrong','	Airborne, Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Daryl','Riley','	Airborne, Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Deanna','Gray','	Airborne, Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Derek','West','	Airborne, Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Derek','Farrell','	Airborne, Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Dexter','Craig','	Airborne, Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Edgar','Owens','	Airborne, Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Edgar','Adams','	Airborne, Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Edith','Cunningham','	Airborne, Inc.');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Edith','Martin','The Government');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Edward','Henderson','The Government');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Edwin','Barnes','The Government');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Elian','Hamilton','The Government');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Elise','Farrell','The Government');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Elise','Crawford','The Government');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Emily','Morgan','The Government');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Emma','Smith','Dunder Mifflin');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Evelyn','Wilson','Dunder Mifflin');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Fenton','Andrews','Dunder Mifflin');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Fiona','Harris','Dunder Mifflin');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Fiona','Jones','Dunder Mifflin');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Florrie','Kelley','Dunder Mifflin');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Frederick','Allen','Dunder Mifflin');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Frederick','Watson','Dunder Mifflin');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('George','Nelson','Dunder Mifflin');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('George','Brown','Dunder Mifflin');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Gianna','Hall','Dunder Mifflin');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Haris','Evans','Dunder Mifflin');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Harold','Richards','Dunder Mifflin');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Heather','Johnston','Yamaha');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Heather','Howard','Yamaha');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Henry','Thompson','Yamaha');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Honey','Morris','Yamaha');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Isabella','Carter','Yamaha');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Jack','Craig','Yamaha');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Jacob','Ryan','Yamaha');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('James','Morris','Yamaha');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('James','Johnston','Yamaha');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Jared','Nelson','Yamaha');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Jasmine','Allen','Yamaha');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Jasmine','Perkins','Yamaha');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Jasmine','Howard','Yamaha');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('John','Crawford','Yamaha');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Jordan','Armstrong','Yamaha');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Jordan','Brooks','Yamaha');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Jordan','Allen','Yamaha');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Joyce','Carroll','Yamaha');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Julia','Dixon','Yamaha');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Julian','Jones','Yamaha');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Julian','Elliott','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Julian','Crawford','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Julian','Warren','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Justin','Hill','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Kate','Hamilton','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Lenny','Kelley','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Leonardo','Miller','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Lucia','Morris','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Lyndon','Adams','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Madaline','Kelly','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Maddie','Cole','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Marcus','Kelley','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Marcus','Cooper','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Martin','West','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Martin','Ellis','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Martin','Perkins','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Mary','West','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Mary','Nelson','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Maximilian','Kelley','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Maya','Holmes','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Maya','Richardson','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Michael','Cunningham','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Michael','Thompson','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Michelle','Douglas','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Michelle','Barrett','Initech');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Miller','Hamilton','LinkedIn');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Miller','Gibson','LinkedIn');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Miranda','Hawkins','LinkedIn');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Naomi','Montgomery','LinkedIn');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Natalie','Higgins','LinkedIn');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Natalie','Barrett','LinkedIn');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Ned','Harper','Jewel Osco');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Nicholas','Morgan','Jewel Osco');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Nicholas','Johnston','Jewel Osco');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Nicole','Myers','Jewel Osco');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Olivia','Myers','Blick');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Oscar','Douglas','Blick');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Paige','Johnston','Blick');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Paul','Barrett','Blick');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Penelope','Bailey','Blick');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Rafael','Hunt','Blick');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Richard','Tucker','Blick');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Richard','Thomas','Blick');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Richard','Morgan','Blick');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Robert','Casey','Blick');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Robert','Hall','Blick');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Roland','Williams','Valve');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Roland','Cooper','Valve');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Roland','Morrison','Valve');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Roland','Phillips','Valve');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Roman','Harris','Valve');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Rubie','Robinson','Valve');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Ryan','Richards','Valve');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Ryan','Walker','Valve');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Sabrina','Casey','Valve');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Sabrina','Watson','Valve');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Sabrina','Thompson','Blick');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Sam','Brooks','Blick');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Samantha','Hawkins','Blick');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Samantha','Craig','Blick');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Sarah','Higgins','Blick');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Sawyer','Alexander','Blick');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Sienna','Cameron','Jewel Osco');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Sofia','Hall','Jewel Osco');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Sofia','Williams','Jewel Osco');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Sophia','Kelly','Jewel Osco');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Spike','Williams','Jewel Osco');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Spike','Barnes','LinkedIn');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Stella','Carter','LinkedIn');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Stella','Adams','LinkedIn');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Steven','Cameron','LinkedIn');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Tess','Morgan','LinkedIn');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Thomas','Walker','LinkedIn');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Thomas','Wilson','LinkedIn');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Thomas','Thompson','LinkedIn');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Thomas','Anderson','LinkedIn');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Thomas','Allen','Duff Beer');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Tiana','Fowler','Duff Beer');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Tony','Stewart','Duff Beer');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Victoria','Douglas','Duff Beer');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Victoria','Lloyd','Duff Beer');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Vincent','Walker','Duff Beer');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Vincent','Evans','Duff Beer');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('Vivian','Myers','Duff Beer');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('William','Martin','Duff Beer');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('William','Montgomery','Duff Beer');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('William','Nelson','Duff Beer');
INSERT INTO customer(first_name,last_name,company_name) VALUES ('William','Payne','Duff Beer');
