# pull the official base image
FROM node:13.12.0-alpine

# set working direction
WORKDIR /react-app

# add `./customer-client/node_modules/.bin` to $PATH

ENV PATH /customer-client/node_modules/.bin:$PATH

# install application dependencies
COPY ./customer-client/package.json ./
COPY ./customer-client/package-lock.json ./

# npm install
RUN npm install

# add app
COPY . ./

# start app
CMD ["npm", "start"]
