# pull the official base image
FROM node:13.12.0-alpine

# set working direction
WORKDIR /react-app

# add `/react-app/node_modules/.bin` to $PATH

ENV PATH /react-app/node_modules/.bin:$PATH

# install application dependencies
COPY ./react-app/package.json ./
COPY ./react-app/package-lock.json ./

RUN npm i
# add app

COPY . ./

# start app
CMD ["npm", "start"]
